Search.appendIndex(
    [
                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive",
            "name": "Drive",
            "summary": "Class\u0020representing\u0020a\u0020single\u0020drive\/space\u0020in\u0020ownCloud\u0020Infinite\u0020Scale",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetAlias\u0028\u0029",
            "name": "getAlias",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getAlias"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getType"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetRoot\u0028\u0029",
            "name": "getRoot",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getRoot"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetWebUrl\u0028\u0029",
            "name": "getWebUrl",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getWebUrl"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetWebDavUrl\u0028\u0029",
            "name": "getWebDavUrl",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getWebDavUrl"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetLastModifiedDateTime\u0028\u0029",
            "name": "getLastModifiedDateTime",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getLastModifiedDateTime"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetQuota\u0028\u0029",
            "name": "getQuota",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getQuota"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetRawData\u0028\u0029",
            "name": "getRawData",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getRawData"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020the\u0020current\u0020drive\u0020irreversibly.",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_delete"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003Adisable\u0028\u0029",
            "name": "disable",
            "summary": "Disables\u0020the\u0020current\u0020drive\u0020without\u0020deleting\u0020it.",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_disable"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_setName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AsetQuota\u0028\u0029",
            "name": "setQuota",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_setQuota"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_setDescription"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AsetImage\u0028\u0029",
            "name": "setImage",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_setImage"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AsetReadme\u0028\u0029",
            "name": "setReadme",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_setReadme"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetResources\u0028\u0029",
            "name": "getResources",
            "summary": "List\u0020the\u0020content\u0020of\u0020a\u0020specific\u0020path\u0020in\u0020the\u0020current\u0020drive",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getResources"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetFile\u0028\u0029",
            "name": "getFile",
            "summary": "Download\u0020and\u0020return\u0020the\u0020content\u0020of\u0020the\u0020file\u0020at\u0020the\u0020given\u0020path\u0020in\u0020the\u0020current\u0020drive",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getFile"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetFileStream\u0028\u0029",
            "name": "getFileStream",
            "summary": "Return\u0020a\u0020stream\u0020resource\u0020for\u0020the\u0020file\u0020at\u0020the\u0020given\u0020path\u0020in\u0020the\u0020current\u0020drive.",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getFileStream"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AcreateFolder\u0028\u0029",
            "name": "createFolder",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_createFolder"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetResourceMetadata\u0028\u0029",
            "name": "getResourceMetadata",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getResourceMetadata"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AgetResourceMetadataById\u0028\u0029",
            "name": "getResourceMetadataById",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_getResourceMetadataById"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AuploadFile\u0028\u0029",
            "name": "uploadFile",
            "summary": "Upload\u0020the\u0020given\u0020content\u0020to\u0020a\u0020specific\u0020path\u0020in\u0020the\u0020current\u0020drive",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_uploadFile"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AuploadFileStream\u0028\u0029",
            "name": "uploadFileStream",
            "summary": "Stream\u0020the\u0020given\u0020resource\u0020to\u0020a\u0020specific\u0020path\u0020in\u0020the\u0020current\u0020drive",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_uploadFileStream"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AdeleteResource\u0028\u0029",
            "name": "deleteResource",
            "summary": "Delete\u0020\u0028move\u0020to\u0020trash\u002Dbin\u0029\u0020the\u0020Ocis\u0020resource\u0020\u0028file\u0020or\u0020folder\u0029\u0020at\u0020the\u0020given\u0020path\u0020in\u0020the\u0020current\u0020drive",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_deleteResource"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AmoveResource\u0028\u0029",
            "name": "moveResource",
            "summary": "Move\u0020or\u0020rename\u0020an\u0020Ocis\u0020resource\u0020in\u0020the\u0020current\u0020drive",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_moveResource"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AemptyTrashbin\u0028\u0029",
            "name": "emptyTrashbin",
            "summary": "Empty\u0020the\u0020trash\u002Dbin\u0020of\u0020the\u0020current\u0020drive.\u0020ALL\u0020FILES\u0020AND\u0020FOLDERS\u0020IN\u0020THE\u0020TRASH\u002DBIN\u0020WILL\u0020BE\u0020DELETED\u0021\nTHIS\u0020ACTION\u0020CANNOT\u0020BE\u0020REVERTED\u0021",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_emptyTrashbin"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AtagResource\u0028\u0029",
            "name": "tagResource",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_tagResource"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Drive\u003A\u003AuntagResource\u0028\u0029",
            "name": "untagResource",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Drive.html#method_untagResource"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveOrder",
            "name": "DriveOrder",
            "summary": "Possible\u0020order\u0020values\u0020for\u0020sorting\u0020a\u0020list\u0020of\u0020drives",
            "url": "classes/Owncloud-OcisPhpSdk-DriveOrder.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveOrder\u003A\u003ALASTMODIFIED",
            "name": "LASTMODIFIED",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-DriveOrder.html#enumcase_LASTMODIFIED"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveOrder\u003A\u003ANAME",
            "name": "NAME",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-DriveOrder.html#enumcase_NAME"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveType",
            "name": "DriveType",
            "summary": "Accepted\u0020drive\u0020types",
            "url": "classes/Owncloud-OcisPhpSdk-DriveType.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveType\u003A\u003APERSONAL",
            "name": "PERSONAL",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-DriveType.html#enumcase_PERSONAL"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveType\u003A\u003APROJECT",
            "name": "PROJECT",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-DriveType.html#enumcase_PROJECT"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveType\u003A\u003AVIRTUAL",
            "name": "VIRTUAL",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-DriveType.html#enumcase_VIRTUAL"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\DriveType\u003A\u003AMOUNTPOINT",
            "name": "MOUNTPOINT",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-DriveType.html#enumcase_MOUNTPOINT"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception\\BadRequestException",
            "name": "BadRequestException",
            "summary": "Exception\u0020for\u0020HTTP\u0020400\u0020errors",
            "url": "classes/Owncloud-OcisPhpSdk-Exception-BadRequestException.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception\\ForbiddenException",
            "name": "ForbiddenException",
            "summary": "Exception\u0020for\u0020HTTP\u0020403\u0020errors",
            "url": "classes/Owncloud-OcisPhpSdk-Exception-ForbiddenException.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception\\HttpException",
            "name": "HttpException",
            "summary": "general\u0020exception\u0020for\u0020HTTP\u0020error\u0020responses\u0020that\u0020are\u0020not\u0020handled\u0020by\u0020the\u0020other\u0020custom\u0020exceptions",
            "url": "classes/Owncloud-OcisPhpSdk-Exception-HttpException.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception\\InvalidResponseException",
            "name": "InvalidResponseException",
            "summary": "Exception\u0020thrown\u0020if\u0020the\u0020ownCloud\u0020Infinite\u0020Scale\u0020server\u0020returns\u0020an\u0020invalid\u0020response.",
            "url": "classes/Owncloud-OcisPhpSdk-Exception-InvalidResponseException.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception\\NotFoundException",
            "name": "NotFoundException",
            "summary": "Exception\u0020for\u0020HTTP\u0020404\u0020errors",
            "url": "classes/Owncloud-OcisPhpSdk-Exception-NotFoundException.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception\\NotImplementedException",
            "name": "NotImplementedException",
            "summary": "Exception\u0020for\u0020functionalities\u0020that\u0020are\u0020planned\u0020but\u0020are\u0020not\u0020implemented\u0020yet",
            "url": "classes/Owncloud-OcisPhpSdk-Exception-NotImplementedException.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception\\UnauthorizedException",
            "name": "UnauthorizedException",
            "summary": "Exception\u0020for\u0020HTTP\u0020401\u0020errors",
            "url": "classes/Owncloud-OcisPhpSdk-Exception-UnauthorizedException.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group",
            "name": "Group",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method___construct"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method_getId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method_getDescription"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003AgetDisplayName\u0028\u0029",
            "name": "getDisplayName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method_getDisplayName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003AgetGroupTypes\u0028\u0029",
            "name": "getGroupTypes",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method_getGroupTypes"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003AgetMembers\u0028\u0029",
            "name": "getMembers",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method_getMembers"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003AaddUser\u0028\u0029",
            "name": "addUser",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method_addUser"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Group\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "delete\u0020an\u0020existing\u0020group\u0020\u0028if\u0020the\u0020user\u0020has\u0020the\u0020permission\u0020to\u0020do\u0020so\u0029",
            "url": "classes/Owncloud-OcisPhpSdk-Group.html#method_delete"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification",
            "name": "Notification",
            "summary": "Class\u0020representing\u0020a\u0020single\u0020notification\u0020emitted\u0020in\u0020ownCloud\u0020Infinite\u0020Scale",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetApp\u0028\u0029",
            "name": "getApp",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getApp"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getUser"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetDatetime\u0028\u0029",
            "name": "getDatetime",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getDatetime"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetObjectId\u0028\u0029",
            "name": "getObjectId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getObjectId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetObjectType\u0028\u0029",
            "name": "getObjectType",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getObjectType"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getSubject"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetSubjectRich\u0028\u0029",
            "name": "getSubjectRich",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getSubjectRich"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getMessage"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetMessageRich\u0028\u0029",
            "name": "getMessageRich",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getMessageRich"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003AgetMessageRichParameters\u0028\u0029",
            "name": "getMessageRichParameters",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_getMessageRichParameters"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Notification\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020\u0028mark\u0020as\u0020read\u0029\u0020the\u0020notification",
            "url": "classes/Owncloud-OcisPhpSdk-Notification.html#method_delete"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis",
            "name": "Ocis",
            "summary": "Basic\u0020class\u0020to\u0020establish\u0020the\u0020connection\u0020to\u0020an\u0020ownCloud\u0020Infinite\u0020Scale\u0020instance",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method___construct"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetServiceUrl\u0028\u0029",
            "name": "getServiceUrl",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getServiceUrl"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AsetAccessToken\u0028\u0029",
            "name": "setAccessToken",
            "summary": "Update\u0020the\u0020access\u0020token.\u0020Call\u0020this\u0020function\u0020after\u0020refreshing\u0020the\u0020access\u0020token.",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_setAccessToken"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetAllDrives\u0028\u0029",
            "name": "getAllDrives",
            "summary": "Get\u0020all\u0020available\u0020drives",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getAllDrives"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetMyDrives\u0028\u0029",
            "name": "getMyDrives",
            "summary": "Get\u0020all\u0020drives\u0020that\u0020the\u0020current\u0020user\u0020is\u0020a\u0020regular\u0020member\u0020of",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getMyDrives"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetDriveById\u0028\u0029",
            "name": "getDriveById",
            "summary": "Retrieve\u0020a\u0020drive\u0020by\u0020its\u0020unique\u0020id",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getDriveById"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AcreateDrive\u0028\u0029",
            "name": "createDrive",
            "summary": "Create\u0020a\u0020new\u0020drive\u0020\u0028if\u0020the\u0020user\u0020has\u0020the\u0020permission\u0020to\u0020do\u0020so\u0029",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_createDrive"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetGroups\u0028\u0029",
            "name": "getGroups",
            "summary": "Get\u0020list\u0020of\u0020groups\u0020\u0028if\u0020the\u0020user\u0020has\u0020the\u0020permission\u0020to\u0020do\u0020so\u0029",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getGroups"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetResourceById\u0028\u0029",
            "name": "getResourceById",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getResourceById"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetUsers\u0028\u0029",
            "name": "getUsers",
            "summary": "retrieve\u0020users\u0020known\u0020by\u0020the\u0020system",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getUsers"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetNotifications\u0028\u0029",
            "name": "getNotifications",
            "summary": "Retrieve\u0020all\u0020unread\u0020notifications\u0020of\u0020the\u0020current\u0020user",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getNotifications"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AcreateGroup\u0028\u0029",
            "name": "createGroup",
            "summary": "Create\u0020a\u0020new\u0020group\u0020\u0028if\u0020the\u0020user\u0020has\u0020the\u0020permission\u0020to\u0020do\u0020so\u0029",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_createGroup"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AdeleteGroupByID\u0028\u0029",
            "name": "deleteGroupByID",
            "summary": "delete\u0020an\u0020existing\u0020group\u0020\u0028if\u0020the\u0020user\u0020has\u0020the\u0020permission\u0020to\u0020do\u0020so\u0029",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_deleteGroupByID"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetSharedWithMe\u0028\u0029",
            "name": "getSharedWithMe",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getSharedWithMe"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AgetSharedByMe\u0028\u0029",
            "name": "getSharedByMe",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#method_getSharedByMe"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Ocis\u003A\u003AFUNCTION_NOT_IMPLEMENTED_YET_ERROR_MESSAGE",
            "name": "FUNCTION_NOT_IMPLEMENTED_YET_ERROR_MESSAGE",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Ocis.html#constant_FUNCTION_NOT_IMPLEMENTED_YET_ERROR_MESSAGE"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource",
            "name": "OcisResource",
            "summary": "Class\u0020representing\u0020a\u0020file\u0020or\u0020folder\u0020inside\u0020a\u0020Drive\u0020in\u0020ownCloud\u0020Infinite\u0020Scale",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "Gets\u0020all\u0020possible\u0020Roles\u0020for\u0020the\u0020resource",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getRoles"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003Ainvite\u0028\u0029",
            "name": "invite",
            "summary": "Invite\u0020one\u0020or\u0020multiple\u0020people\u0028user\/group\u0029\u0020to\u0020the\u0020resource.",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_invite"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AcreateSharingLink\u0028\u0029",
            "name": "createSharingLink",
            "summary": "create\u0020a\u0020new\u0020\u0028public\u0029\u0020link",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_createSharingLink"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetSpaceId\u0028\u0029",
            "name": "getSpaceId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getSpaceId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetParent\u0028\u0029",
            "name": "getParent",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getParent"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetEtag\u0028\u0029",
            "name": "getEtag",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getEtag"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetPermission\u0028\u0029",
            "name": "getPermission",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getPermission"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getType"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetSize\u0028\u0029",
            "name": "getSize",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getSize"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetLastModifiedTime\u0028\u0029",
            "name": "getLastModifiedTime",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getLastModifiedTime"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetContentType\u0028\u0029",
            "name": "getContentType",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getContentType"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getTags"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AisFavorited\u0028\u0029",
            "name": "isFavorited",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_isFavorited"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetCheckSums\u0028\u0029",
            "name": "getCheckSums",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getCheckSums"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetPrivatelink\u0028\u0029",
            "name": "getPrivatelink",
            "summary": "Returns\u0020the\u0020private\u0020link\u0020to\u0020the\u0020resource.",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getPrivatelink"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getContent"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetContentStream\u0028\u0029",
            "name": "getContentStream",
            "summary": "returns\u0020a\u0020stream\u0020to\u0020get\u0020the\u0020content\u0020of\u0020this\u0020resource",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getContentStream"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OcisResource\u003A\u003AgetDriveId\u0028\u0029",
            "name": "getDriveId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OcisResource.html#method_getDriveId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OrderDirection",
            "name": "OrderDirection",
            "summary": "Possible\u0020order\u0020direction\u0020values\u0020for\u0020sorting\u0020responses",
            "url": "classes/Owncloud-OcisPhpSdk-OrderDirection.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OrderDirection\u003A\u003AASC",
            "name": "ASC",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OrderDirection.html#enumcase_ASC"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\OrderDirection\u003A\u003ADESC",
            "name": "DESC",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-OrderDirection.html#enumcase_DESC"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Share",
            "name": "Share",
            "summary": "Parent\u0020class\u0020representing\u0020different\u0020types\u0020of\u0020share\u0020objects",
            "url": "classes/Owncloud-OcisPhpSdk-Share.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Share\u003A\u003AgetPermissionId\u0028\u0029",
            "name": "getPermissionId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Share.html#method_getPermissionId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Share\u003A\u003AgetExpiry\u0028\u0029",
            "name": "getExpiry",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-Share.html#method_getExpiry"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Share\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Permanently\u0020delete\u0020the\u0020current\u0020share\u0020or\u0020share\u0020link",
            "url": "classes/Owncloud-OcisPhpSdk-Share.html#method_delete"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Share\u003A\u003AsetExpiration\u0028\u0029",
            "name": "setExpiration",
            "summary": "Change\u0020the\u0020Expiration\u0020date\u0020for\u0020the\u0020current\u0020share\u0020or\u0020share\u0020link\nSet\u0020to\u0020null\u0020to\u0020remove\u0020the\u0020expiration\u0020date",
            "url": "classes/Owncloud-OcisPhpSdk-Share.html#method_setExpiration"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareCreated",
            "name": "ShareCreated",
            "summary": "Parent\u0020class\u0020representing\u0020different\u0020types\u0020of\u0020share\u0020objects",
            "url": "classes/Owncloud-OcisPhpSdk-ShareCreated.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareCreated\u003A\u003AgetPermissionId\u0028\u0029",
            "name": "getPermissionId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareCreated.html#method_getPermissionId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareCreated\u003A\u003AsetRole\u0028\u0029",
            "name": "setRole",
            "summary": "Change\u0020the\u0020Role\u0020of\u0020the\u0020particular\u0020Share.",
            "url": "classes/Owncloud-OcisPhpSdk-ShareCreated.html#method_setRole"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink",
            "name": "ShareLink",
            "summary": "Class\u0020representing\u0020a\u0020public\u0020link\u0020to\u0020a\u0020resource",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "phan\u002Dsuppress\u002Dnext\u002Dline\u0020PhanTypeMismatchReturnNullable",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html#method_getType"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink\u003A\u003AgetWebUrl\u0028\u0029",
            "name": "getWebUrl",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html#method_getWebUrl"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink\u003A\u003AgetDisplayName\u0028\u0029",
            "name": "getDisplayName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html#method_getDisplayName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink\u003A\u003AsetDisplayName\u0028\u0029",
            "name": "setDisplayName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html#method_setDisplayName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink\u003A\u003AsetType\u0028\u0029",
            "name": "setType",
            "summary": "Change\u0020the\u0020type\u0020of\u0020the\u0020current\u0020ShareLink.",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html#method_setType"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html#method_setPassword"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareLink\u003A\u003AupdateLinkOfPermission\u0028\u0029",
            "name": "updateLinkOfPermission",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareLink.html#method_updateLinkOfPermission"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved",
            "name": "ShareRecieved",
            "summary": "Ensures\u0020that\u0020the\u0020return\u0020type\u0020is\u0020correct,\u0020but\u0020Phan\u0020does\u0020not\u0020recognize\u0020it.",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method___construct"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetEtag\u0028\u0029",
            "name": "getEtag",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getEtag"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetDriveId\u0028\u0029",
            "name": "getDriveId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getDriveId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetDriveType\u0028\u0029",
            "name": "getDriveType",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getDriveType"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetRemoteItemId\u0028\u0029",
            "name": "getRemoteItemId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getRemoteItemId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetRemoteItemName\u0028\u0029",
            "name": "getRemoteItemName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getRemoteItemName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetRemoteItemSize\u0028\u0029",
            "name": "getRemoteItemSize",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getRemoteItemSize"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetRemoteItemSharedDateTime\u0028\u0029",
            "name": "getRemoteItemSharedDateTime",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getRemoteItemSharedDateTime"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetOwnerName\u0028\u0029",
            "name": "getOwnerName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getOwnerName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003AgetOwnerId\u0028\u0029",
            "name": "getOwnerId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_getOwnerId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_accept"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\ShareRecieved\u003A\u003Adecline\u0028\u0029",
            "name": "decline",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-ShareRecieved.html#method_decline"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\SharingRole",
            "name": "SharingRole",
            "summary": "class\u0020to\u0020define\u0020a\u0020role\u0020of\u0020a\u0020user\u0020or\u0020group\u0020in\u0020a\u0020share\nevery\u0020role\u0020contains\u0020specific\u0020permissions",
            "url": "classes/Owncloud-OcisPhpSdk-SharingRole.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\SharingRole\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-SharingRole.html#method_getId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\SharingRole\u003A\u003AgetDisplayName\u0028\u0029",
            "name": "getDisplayName",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-SharingRole.html#method_getDisplayName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\SharingRole\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-SharingRole.html#method_getDescription"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\SharingRole\u003A\u003AgetWeight\u0028\u0029",
            "name": "getWeight",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-SharingRole.html#method_getWeight"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\User",
            "name": "User",
            "summary": "",
            "url": "classes/Owncloud-OcisPhpSdk-User.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\User\u003A\u003AgetDisplayName\u0028\u0029",
            "name": "getDisplayName",
            "summary": "Get\u0020the\u0020value\u0020of\u0020displayName",
            "url": "classes/Owncloud-OcisPhpSdk-User.html#method_getDisplayName"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Get\u0020the\u0020value\u0020of\u0020id",
            "url": "classes/Owncloud-OcisPhpSdk-User.html#method_getId"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\User\u003A\u003AgetMail\u0028\u0029",
            "name": "getMail",
            "summary": "Get\u0020the\u0020value\u0020of\u0020email",
            "url": "classes/Owncloud-OcisPhpSdk-User.html#method_getMail"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\User\u003A\u003AgetOnPremisesSamAccountName\u0028\u0029",
            "name": "getOnPremisesSamAccountName",
            "summary": "Get\u0020the\u0020value\u0020of\u0020onPremisesSamAccountName",
            "url": "classes/Owncloud-OcisPhpSdk-User.html#method_getOnPremisesSamAccountName"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota",
            "name": "Quota",
            "summary": "Quota\u0020Class\u0020Doc\u0020Comment",
            "url": "classes/OpenAPI-Client-Model-Quota.html"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AopenAPITypes\u0028\u0029",
            "name": "openAPITypes",
            "summary": "Array\u0020of\u0020property\u0020to\u0020type\u0020mappings.\u0020Used\u0020for\u0020\u0028de\u0029serialization",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_openAPITypes"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AopenAPIFormats\u0028\u0029",
            "name": "openAPIFormats",
            "summary": "Array\u0020of\u0020property\u0020to\u0020format\u0020mappings.\u0020Used\u0020for\u0020\u0028de\u0029serialization",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_openAPIFormats"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AisNullable\u0028\u0029",
            "name": "isNullable",
            "summary": "Checks\u0020if\u0020a\u0020property\u0020is\u0020nullable",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_isNullable"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AisNullableSetToNull\u0028\u0029",
            "name": "isNullableSetToNull",
            "summary": "Checks\u0020if\u0020a\u0020nullable\u0020property\u0020is\u0020set\u0020to\u0020null.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_isNullableSetToNull"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AattributeMap\u0028\u0029",
            "name": "attributeMap",
            "summary": "Array\u0020of\u0020attributes\u0020where\u0020the\u0020key\u0020is\u0020the\u0020local\u0020name,\nand\u0020the\u0020value\u0020is\u0020the\u0020original\u0020name",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_attributeMap"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003Asetters\u0028\u0029",
            "name": "setters",
            "summary": "Array\u0020of\u0020attributes\u0020to\u0020setter\u0020functions\u0020\u0028for\u0020deserialization\u0020of\u0020responses\u0029",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_setters"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003Agetters\u0028\u0029",
            "name": "getters",
            "summary": "Array\u0020of\u0020attributes\u0020to\u0020getter\u0020functions\u0020\u0028for\u0020serialization\u0020of\u0020requests\u0029",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_getters"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AgetModelName\u0028\u0029",
            "name": "getModelName",
            "summary": "The\u0020original\u0020name\u0020of\u0020the\u0020model.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_getModelName"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method___construct"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AlistInvalidProperties\u0028\u0029",
            "name": "listInvalidProperties",
            "summary": "Show\u0020all\u0020the\u0020invalid\u0020properties\u0020with\u0020reasons.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_listInvalidProperties"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "Validate\u0020all\u0020the\u0020properties\u0020in\u0020the\u0020model\nreturn\u0020true\u0020if\u0020all\u0020passed",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_valid"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AgetDeleted\u0028\u0029",
            "name": "getDeleted",
            "summary": "Gets\u0020deleted",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_getDeleted"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AsetDeleted\u0028\u0029",
            "name": "setDeleted",
            "summary": "Sets\u0020deleted",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_setDeleted"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AgetRemaining\u0028\u0029",
            "name": "getRemaining",
            "summary": "Gets\u0020remaining",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_getRemaining"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AsetRemaining\u0028\u0029",
            "name": "setRemaining",
            "summary": "Sets\u0020remaining",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_setRemaining"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "Gets\u0020state",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_getState"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AsetState\u0028\u0029",
            "name": "setState",
            "summary": "Sets\u0020state",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_setState"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AgetTotal\u0028\u0029",
            "name": "getTotal",
            "summary": "Gets\u0020total",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_getTotal"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AsetTotal\u0028\u0029",
            "name": "setTotal",
            "summary": "Sets\u0020total",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_setTotal"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AgetUsed\u0028\u0029",
            "name": "getUsed",
            "summary": "Gets\u0020used",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_getUsed"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AsetUsed\u0028\u0029",
            "name": "setUsed",
            "summary": "Sets\u0020used",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_setUsed"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Returns\u0020true\u0020if\u0020offset\u0020exists.\u0020False\u0020otherwise.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_offsetExists"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Gets\u0020offset.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_offsetGet"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Sets\u0020value\u0020based\u0020on\u0020offset.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_offsetSet"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Unsets\u0020offset.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_offsetUnset"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "Serializes\u0020the\u0020object\u0020to\u0020a\u0020value\u0020that\u0020can\u0020be\u0020serialized\u0020natively\u0020by\u0020json_encode\u0028\u0029.",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_jsonSerialize"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Gets\u0020the\u0020string\u0020presentation\u0020of\u0020the\u0020object",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method___toString"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003AtoHeaderValue\u0028\u0029",
            "name": "toHeaderValue",
            "summary": "Gets\u0020a\u0020header\u002Dsafe\u0020presentation\u0020of\u0020the\u0020object",
            "url": "classes/OpenAPI-Client-Model-Quota.html#method_toHeaderValue"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\Quota\u003A\u003ADISCRIMINATOR",
            "name": "DISCRIMINATOR",
            "summary": "",
            "url": "classes/OpenAPI-Client-Model-Quota.html#constant_DISCRIMINATOR"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\SharingLinkType",
            "name": "SharingLinkType",
            "summary": "SharingLinkType\u0020Class\u0020Doc\u0020Comment",
            "url": "classes/OpenAPI-Client-Model-SharingLinkType.html"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\SharingLinkType\u003A\u003AINTERNAL",
            "name": "INTERNAL",
            "summary": "",
            "url": "classes/OpenAPI-Client-Model-SharingLinkType.html#enumcase_INTERNAL"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\SharingLinkType\u003A\u003AVIEW",
            "name": "VIEW",
            "summary": "",
            "url": "classes/OpenAPI-Client-Model-SharingLinkType.html#enumcase_VIEW"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\SharingLinkType\u003A\u003AUPLOAD",
            "name": "UPLOAD",
            "summary": "",
            "url": "classes/OpenAPI-Client-Model-SharingLinkType.html#enumcase_UPLOAD"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\SharingLinkType\u003A\u003AEDIT",
            "name": "EDIT",
            "summary": "",
            "url": "classes/OpenAPI-Client-Model-SharingLinkType.html#enumcase_EDIT"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\SharingLinkType\u003A\u003ACREATE_ONLY",
            "name": "CREATE_ONLY",
            "summary": "",
            "url": "classes/OpenAPI-Client-Model-SharingLinkType.html#enumcase_CREATE_ONLY"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model\\SharingLinkType\u003A\u003ABLOCKS_DOWNLOAD",
            "name": "BLOCKS_DOWNLOAD",
            "summary": "",
            "url": "classes/OpenAPI-Client-Model-SharingLinkType.html#enumcase_BLOCKS_DOWNLOAD"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk",
            "name": "OcisPhpSdk",
            "summary": "",
            "url": "namespaces/owncloud-ocisphpsdk.html"
        },                {
            "fqsen": "\\Owncloud",
            "name": "Owncloud",
            "summary": "",
            "url": "namespaces/owncloud.html"
        },                {
            "fqsen": "\\Owncloud\\OcisPhpSdk\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/owncloud-ocisphpsdk-exception.html"
        },                {
            "fqsen": "\\OpenAPI\\Client\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/openapi-client-model.html"
        },                {
            "fqsen": "\\OpenAPI\\Client",
            "name": "Client",
            "summary": "",
            "url": "namespaces/openapi-client.html"
        },                {
            "fqsen": "\\OpenAPI",
            "name": "OpenAPI",
            "summary": "",
            "url": "namespaces/openapi.html"
        }            ]
);
